### ISSUE TITLE
Icon and Application name

### ISSUE THREAD

**Issue by Zaid-Ajaj** [Zaid-Ajaj/fsharp-weekly#1]
I am probably doing something wrong here but I can't get the icon and application name to change when deployed to the store

**Comment by SergejDK** [comment]
The following part you need to change: 
`[<Activity (Label = "F# Weekly", Icon = "@mipmap/icon", Theme = "@style/MainTheme", MainLauncher = true, ConfigurationChanges = (ConfigChanges.ScreenSize ||| ConfigChanges.Orientation))>]`

Change the label and the icon and you are good to go!

**Comment by Zaid-Ajaj** [comment]
Changed the attribute to:
```fs
[<Activity (Label = "F# Weekly", Icon = "@mipmap/icon", Theme = "@style/MainTheme", MainLauncher = true, ConfigurationChanges = (ConfigChanges.ScreenSize ||| ConfigChanges.Orientation))>]
```
and the title works! :tada: and all the icons in `mpimap` to fsharp icon but I still got the xamarin icon displayed when I deploy in debug mode, then I saw the files `icon.xml` and `icon_round.xml` which contain:
```xml
<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/launcher_background" />
    <foreground android:drawable="@mipmap/launcher_foreground" />
</adaptive-icon>
```
if I change the content to:
```xml
<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/launcher_background" />
    <foreground android:drawable="@mipmap/icon" />
</adaptive-icon>
```
then I get the default android icon (which I think means that it couldn't find the icon in question)

**Comment by SergejDK** [comment]
Normally this is a Clean and Rebuild failure but this is not the case here. I need to take a closer look on this.

**Comment by SergejDK** [comment]
So here is the solution even though I do not know why the name `icon` can not be used.

Change the name of the `Icon.png` to sth. else e.g. `Appicon.png` in each `mipmap-folder`.
Then change the xml-files to `@mipmap/appicon`.
Set the icon in the `manifest.xml` file, too.

At last you can add a `round_icon` to the mainactivity: 
```fsharp
[<Activity (Label = "F# Weekly", Icon = "@mipmap/icon", RoundIcon = "@mipmap/icon_round", Theme = "@style/MainTheme", MainLauncher = true, ConfigurationChanges = (ConfigChanges.ScreenSize ||| ConfigChanges.Orientation))>]
```

After all this just delete the `obj` Folder in the Android project and clean the project to be safe!

**Comment by Zaid-Ajaj** [comment]
Thank you so much @SergejDK, I followed your instructions and the icon/app name changed! I will release when I have a better internet connection (train WiFi for now)
