### ISSUE TITLE
Error while loading blog entries

### ISSUE THREAD

**Issue by ma3yta** [Zaid-Ajaj/fsharp-weekly#13]
https://pasteboard.co/I4Y6kjn.png

**Comment by Zaid-Ajaj** [comment]
Hello @Ma3yTa, I have seen the error too, I suspect something went wrong when scraping the F# weekly website, will take a look soon

**Comment by Zaid-Ajaj** [comment]
A new version has been rolled out that fixes this issue, please update when it becomes available :smile:
