### ISSUE TITLE
Error accesing GitHub

### ISSUE THREAD

**Issue by srlopez** [Zaid-Ajaj/fsharp-weekly#15]
Since two days ago.
Only accesing GitHub.

![Screenshot_20190613-143841](https://user-images.githubusercontent.com/94729/59433131-263dee00-8de9-11e9-9ff4-4e541f30eef5.png)

**Comment by Zaid-Ajaj** [comment]
Maybe Github changed the layout of their trending page, I will take a look, thanks for filing the issue!

**Comment by srlopez** [comment]
Have you updated the app un the Android AppStore?

**Comment by Zaid-Ajaj** [comment]
@srlopez Sorry not yet, didn't have time to look into this one, will try to publish a new version this week
