### ISSUE TITLE
GitHub repos not syncing

### ISSUE THREAD

**Issue by MikeCheque** [Zaid-Ajaj/fsharp-weekly#22]
![Feb-16,-2020-1-04-49-PM](https://user-images.githubusercontent.com/45575396/74610020-86460c00-50bd-11ea-90a2-722a72ae3d73.jpg)

**Comment by FoggyFinder** [comment]
Duplicate of #20  ?

**Comment by MikeCheque** [comment]
@FoggyFinder my mistake. I guess i didn't look hard enough when I initially searched.
