### ISSUE TITLE
High resolution icons for Android

### ISSUE THREAD

**Issue by Zaid-Ajaj** [Zaid-Ajaj/fsharp-weekly#5]
Now that #1 is fixed, it would be nice to have high resolution F# icons with appropriate sizes and aspect-ratios. PR's are welcome

**Comment by SergejDK** [comment]
Do you mean the application icon? 

If so then this thing can be great: [https://romannurik.github.io/AndroidAssetStudio/icons-launcher.html#foreground.type=clipart&foreground.clipart=android&foreground.space.trim=1&foreground.space.pad=0.25&foreColor=rgba(96%2C%20125%2C%20139%2C%200)&backColor=rgb(68%2C%20138%2C%20255)&crop=0&backgroundShape=square&effects=none&name=ic_launcher](https://romannurik.github.io/AndroidAssetStudio/icons-launcher.html#foreground.type=clipart&foreground.clipart=android&foreground.space.trim=1&foreground.space.pad=0.25&foreColor=rgba(96%2C%20125%2C%20139%2C%200)&backColor=rgb(68%2C%20138%2C%20255)&crop=0&backgroundShape=square&effects=none&name=ic_launcher)

**Comment by kunjee17** [comment]
@Zaid-Ajaj  I have added icons for iOS, Android and Watch. Do have a look at it. 

It is already in PR.

**Comment by Zaid-Ajaj** [comment]
That website is really really cool @SergejDK I ended up using one of @kunjee17's high resolution icons as base icon and it generated the rest, very helpful! I published a new android version with the icons. Thanks a lot :heart:
