### ISSUE TITLE
Provide privacy policy URL

### ISSUE THREAD

**Issue by kunjee17** [Zaid-Ajaj/fsharp-weekly#8]
Hi, @Zaid-Ajaj  can you please provide privacy policy url. You need to change settings to take docs as basic documentation and then provide me the link. 

PS: You can put index page as well to provide links to Android store app, (and later app store app)

**Comment by Zaid-Ajaj** [comment]
Do you mean to publish the docs directory to github-pages and make them publicly available?

**Comment by Zaid-Ajaj** [comment]
Here you go https://zaid-ajaj.github.io/fsharp-weekly/privacy_policy.html

**Comment by kunjee17** [comment]
Thanks man... Closing the issue as of now.
